#!/usr/bin/env python3
import itertools
import typing as T
from copy import deepcopy
from dataclasses import dataclass
from pathlib import Path


def part1(seq: T.List[int], number: int) -> T.List[int]:
    seq = seq[:]
    x = 0
    y = 1
    while True:
        num = seq[x] + seq[y]
        if num // 10:
            seq.append(num // 10)
        seq.append(num % 10)
        x = (x + 1 + seq[x]) % len(seq)
        y = (y + 1 + seq[y]) % len(seq)
        if len(seq) >= 10 + number:
            return seq[number:number+10]


def main() -> None:
    number = int(Path(__file__).with_name("input.txt").read_text())

    print("".join(map(str, part1([3, 7], number))))


if __name__ == "__main__":
    main()
