#!/usr/bin/env python3
import sys
import typing as T
from pathlib import Path


def part1(seq: T.List[int], number: int) -> T.List[int]:
    seq = seq[:]

    x, y = 0, 1
    while True:
        num = seq[x] + seq[y]

        if num // 10:
            seq.append(num // 10)
        seq.append(num % 10)

        x = (x + 1 + seq[x]) % len(seq)
        y = (y + 1 + seq[y]) % len(seq)

        if len(seq) >= 10 + number:
            return seq[number : number + 10]


def part2(seq: T.List[int], number: int) -> int:
    seq = seq[:]
    needle = list(map(int, str(number)))
    needle_size = len(needle)

    x, y = 0, 1
    while True:
        num = seq[x] + seq[y]

        if num // 10:
            seq.append(num // 10)
            if seq[-needle_size - 1 : -1] == needle:
                return len(seq) - 1 - needle_size

        seq.append(num % 10)
        if seq[-needle_size - 1 : -1] == needle:
            return len(seq) - 1 - needle_size

        x = (x + 1 + seq[x]) % len(seq)
        y = (y + 1 + seq[y]) % len(seq)


def main() -> None:
    number = int(Path(__file__).with_name("input.txt").read_text())

    print("".join(map(str, part1([3, 7], number))))
    print(part2([3, 7], number))


if __name__ == "__main__":
    main()
