#!/usr/bin/env python3
import enum
import re
import typing as T
from copy import copy
from dataclasses import dataclass
from pathlib import Path

REGISTER_COUNT = 4


class Opcode(enum.IntEnum):
    addr = enum.auto()  # add register
    addi = enum.auto()  # add immediate
    mulr = enum.auto()  # multiply register
    muli = enum.auto()  # multiply immediate
    banr = enum.auto()  # bitwise AND register
    bani = enum.auto()  # bitwise AND immediate
    borr = enum.auto()  # bitwise OR register
    bori = enum.auto()  # bitwise OR immediate
    setr = enum.auto()  # set register
    seti = enum.auto()  # set immediate
    gtir = enum.auto()  # greater-than immediate/register
    gtri = enum.auto()  # greater-than register/immediate
    gtrr = enum.auto()  # greater-than register/register
    eqir = enum.auto()  # equal immediate/register
    eqri = enum.auto()  # equal register/immediate
    eqrr = enum.auto()  # equal register/register


@dataclass
class Instruction:
    opcode_num: int
    arg1: int
    arg2: int
    out: int


@dataclass
class Sample:
    before: T.List[int]
    after: T.List[int]
    instruction: Instruction


def calc(
    registers: T.List[int], opcode: Opcode, arg1: int, arg2: int, out: int
) -> None:
    opcode_func: T.Dict[Opcode, T.Callable[[int, int], int]] = {
        Opcode.addr: lambda a, b: registers[a] + registers[b],
        Opcode.addi: lambda a, b: registers[a] + b,
        Opcode.mulr: lambda a, b: registers[a] * registers[b],
        Opcode.muli: lambda a, b: registers[a] * b,
        Opcode.banr: lambda a, b: registers[a] & registers[b],
        Opcode.bani: lambda a, b: registers[a] & b,
        Opcode.borr: lambda a, b: registers[a] | registers[b],
        Opcode.bori: lambda a, b: registers[a] | b,
        Opcode.setr: lambda a, _: registers[a],
        Opcode.seti: lambda a, _: a,
        Opcode.gtir: lambda a, b: int(a > registers[b]),
        Opcode.gtri: lambda a, b: int(registers[a] > b),
        Opcode.gtrr: lambda a, b: int(registers[a] > registers[b]),
        Opcode.eqir: lambda a, b: int(a == registers[b]),
        Opcode.eqri: lambda a, b: int(registers[a] == b),
        Opcode.eqrr: lambda a, b: int(registers[a] == registers[b]),
    }
    registers[out] = opcode_func[opcode](arg1, arg2)


def find_matching_opcodes(
    sample: Sample, remaining: T.Iterable[Opcode]
) -> T.Iterable[Opcode]:
    for opcode in remaining:
        registers = copy(sample.before)
        calc(
            registers,
            opcode,
            sample.instruction.arg1,
            sample.instruction.arg2,
            sample.instruction.out,
        )
        if registers == sample.after:
            yield opcode


def figure_opcode_mapping(samples: T.List[Sample]) -> T.Dict[int, Opcode]:
    confirmed: T.Dict[int, Opcode] = {}
    remaining: T.Set[Opcode] = set(Opcode)

    while remaining:
        product: T.Dict[int, T.Set[Opcode]] = {}
        for sample in samples:
            opcodes = list(find_matching_opcodes(sample, remaining))
            if sample.instruction.opcode_num in product:
                product[sample.instruction.opcode_num].intersection_update(
                    set(opcodes)
                )
            else:
                product[sample.instruction.opcode_num] = set(opcodes)

        for num, possible_opcodes in product.items():
            if len(possible_opcodes) == 1:
                to_remove = next(iter(possible_opcodes))
                remaining.discard(to_remove)
                confirmed[num] = to_remove

    return confirmed


def part1(samples: T.List[Sample]) -> int:
    total = 0
    for sample in samples:
        opcodes = list(find_matching_opcodes(sample, set(Opcode)))
        if len(opcodes) >= 3:
            total += 1
    return total


def part2(samples: T.List[Sample], instructions: T.List[Instruction]) -> int:
    num_to_opcode = figure_opcode_mapping(samples)

    registers = [0] * REGISTER_COUNT
    for instruction in instructions:
        calc(
            registers,
            num_to_opcode[instruction.opcode_num],
            instruction.arg1,
            instruction.arg2,
            instruction.out,
        )
    return registers[0]


def get_numbers(text: str) -> T.List[int]:
    return list(map(int, re.findall(r"-?\d+", text)))


def parse_instruction(text: str) -> Instruction:
    numbers = get_numbers(text)
    return Instruction(
        opcode_num=numbers[0], arg1=numbers[1], arg2=numbers[2], out=numbers[3]
    )


def parse_input_file(
    text: str
) -> T.Tuple[T.List[Sample], T.List[Instruction]]:
    samples: T.List[Sample] = []
    instructions: T.List[Instruction] = []

    for chunk in text.split("\n\n\n")[0].split("\n\n"):
        lines = chunk.split("\n")
        before = get_numbers(lines[0])
        after = get_numbers(lines[2])
        instruction = parse_instruction(lines[1])

        samples.append(
            Sample(before=before, after=after, instruction=instruction)
        )

    for line in text.split("\n\n\n")[1].split("\n"):
        if line:
            instruction = parse_instruction(line)
            instructions.append(instruction)

    return samples, instructions


def main() -> None:
    text = Path(__file__).with_name("input.txt").read_text()
    samples, instructions = parse_input_file(text)

    print(part1(samples))
    print(part2(samples, instructions))


if __name__ == "__main__":
    main()
