#!/usr/bin/env python3
import re
import typing as T
from collections import defaultdict
from pathlib import Path


def part1(players: int, highest_marble: int) -> int:
    ring = [0]
    current = 1
    marbles = list(range(1, highest_marble + 1))
    scores: T.Dict[int, int] = defaultdict(int)
    for i, marble in enumerate(marbles):
        player = i % players
        if marble % 23 == 0:
            scores[player] += marble
            current = (current - 7) % len(ring)
            scores[player] += ring[current]
            del ring[current]
        else:
            current = (current + 1) % len(ring) + 1
            ring.insert(current, marble)
    return max(scores.values())


def main() -> None:
    text = Path(__file__).with_name("input.txt").read_text()
    players, highest_marble = map(int, re.findall(r"\d+", text))

    print(part1(players, highest_marble))


if __name__ == "__main__":
    main()
