#!/usr/bin/env python3
import re
from pathlib import Path


def part1(lines):
    def is_nice(word):
        if re.search("ab|cd|pq|xy", word):
            return False
        if len(re.findall("[aeiou]", word)) < 3:
            return False
        if not re.search(r"(.)\1", word):
            return False
        return True

    return sum(1 for line in lines if is_nice(line))


def part2(lines):
    def is_nice(word):
        if not re.search(r"(..).*\1", word):
            return False
        if not re.search(r"(.).\1", word):
            return False
        return True

    return sum(1 for line in lines if is_nice(line))


if __name__ == "__main__":
    with Path("input.txt").open() as handle:
        lines = [line.rstrip() for line in handle]
        print(part1(lines))
        print(part2(lines))
