#!/usr/bin/env python3
import re
import typing as T
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path


@dataclass
class Claim:
    id_: int
    x: int
    y: int
    w: int
    h: int

    @property
    def x2(self) -> int:
        return self.x + self.w

    @property
    def y2(self) -> int:
        return self.y + self.h

    @staticmethod
    def from_string(line: str) -> "Claim":
        id_, x, y, w, h = list(map(int, re.findall(r"\d+", line)))
        return Claim(id_=id_, x=x, y=y, w=w, h=h)


def part1(claims: T.List[Claim]) -> int:
    area: T.Dict[T.Tuple[int, int], int] = defaultdict(int)
    for claim in claims:
        for y in range(claim.y, claim.y2):
            for x in range(claim.x, claim.x2):
                area[x, y] += 1
    return sum(1 for num in area.values() if num >= 2)


def part2(claims: T.List[Claim]) -> int:
    area: T.Dict[T.Tuple[int, int], T.List[Claim]] = defaultdict(list)
    for claim in claims:
        for y in range(claim.y, claim.y2):
            for x in range(claim.x, claim.x2):
                area[x, y].append(claim)
    singles: T.List[Claim] = []
    for claim in claims:
        single = True
        for y in range(claim.y, claim.y2):
            for x in range(claim.x, claim.x2):
                if len(area[x, y]) > 1:
                    single = False
        if single:
            singles.append(claim)
    assert len(singles) == 1
    return singles[0].id_


def main() -> None:
    with Path(__file__).with_name("input.txt").open() as handle:
        claims = list(map(Claim.from_string, handle))

    print(part1(claims))
    print(part2(claims))


if __name__ == "__main__":
    main()
