#!/usr/bin/env python3
import re
from pathlib import Path


def part1(document):
    matches = re.finditer(r'-?\d+', document)
    return sum(int(match.group(0)) for match in matches)


if __name__ == "__main__":
    document = Path(__file__).with_name("input.txt").read_text().strip()
    print(part1(document))
