#!/usr/bin/env python3
from pathlib import Path


def is_nice(word):
    for part in ["ab", "cd", "pq", "xy"]:
        if part in word:
            return False

    vowels = 0
    double = False
    prev_char = None

    for char in word:
        if char in "aeiou":
            vowels += 1

        if char == prev_char:
            double = True
        prev_char = char

    return vowels >= 3 and double


def part1(lines):
    return sum(1 for line in lines if is_nice(line))


if __name__ == "__main__":
    with Path("input.txt").open() as handle:
        lines = [line.rstrip() for line in handle]
        print(part1(lines))
