#!/usr/bin/env python3
from hashlib import md5
from itertools import count
from pathlib import Path


def get_hash(text):
    return md5(text.encode()).hexdigest()


def part1(word):
    for i in count(start=1):
        if get_hash(word + str(i)).startswith("0" * 5):
            return i


def part2(word):
    for i in count(start=1):
        if get_hash(word + str(i)).startswith("0" * 6):
            return i


if __name__ == "__main__":
    word = Path("input.txt").read_text().rstrip()
    print(part1(word))
    print(part2(word))
