#!/usr/bin/env python3
import datetime
import enum
import re
import typing as T
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

import dateutil.parser


class EventType(enum.Enum):
    begin_shift = 1
    fall_asleep = 2
    wake_up = 3


@dataclass
class Event:
    date: datetime.datetime
    text: str
    guard_id: int
    event_type: EventType

    @staticmethod
    def from_line(line: str, prev_event: T.Optional["Event"]) -> "Event":
        line = line.strip()
        match = re.match("\[([^\]]+)\]", line)
        assert match
        date = dateutil.parser.parse(match.group(1))
        match = re.search("Guard #(\d+)", line)
        if match:
            guard_id = int(match.group(1))
            event_type = EventType.begin_shift
        else:
            assert prev_event
            guard_id = prev_event.guard_id
            if "wakes up" in line:
                event_type = EventType.wake_up
            elif "falls asleep" in line:
                event_type = EventType.fall_asleep
            else:
                assert False, "unknown event type"
        return Event(
            date=date, text=line, guard_id=guard_id, event_type=event_type
        )


def get_guard_minutes(events: T.List[Event]) -> T.Dict[T.Tuple[int, int], int]:
    guard_minutes: T.Dict[T.Tuple[int, int], int] = defaultdict(int)
    guard_id: int = -1
    fell_asleep_at: T.Optional[datetime.datetime] = None
    queue = events[:]
    while queue:
        event = queue.pop(0)
        if event.event_type == EventType.fall_asleep:
            fell_asleep_at = event.date
            guard_id = event.guard_id
        elif event.event_type == EventType.wake_up:
            assert fell_asleep_at, event.date
            assert event.guard_id == guard_id
            for minute in range(fell_asleep_at.minute, event.date.minute):
                guard_minutes[guard_id, minute] += 1
            fell_asleep_at = None
            guard_id = -1
    return guard_minutes


def get_sleep_times(
    guard_minutes: T.Dict[T.Tuple[int, int], int]
) -> T.Dict[int, int]:
    sleep_times: T.Dict[int, int] = defaultdict(int)
    for key, sleep_time in guard_minutes.items():
        guard_id, _minute = key
        sleep_times[guard_id] += sleep_time
    return sleep_times


def part1(events: T.List[Event]) -> int:
    guard_minutes = get_guard_minutes(events)
    sleep_times = get_sleep_times(guard_minutes)
    sleepiest_guard_id = max(sleep_times.items(), key=lambda kv: kv[1])[0]
    safest_minute = max(
        range(60), key=lambda minute: guard_minutes[sleepiest_guard_id, minute]
    )
    return sleepiest_guard_id * safest_minute


def part2(events: T.List[Event]) -> int:
    guard_minutes = get_guard_minutes(events)
    guard_ids = set(event.guard_id for event in events)

    sleep_time = 0
    sleepiest_guard_id = 0
    safest_minute = 0
    for minute in range(60):
        sleepiest_guard_id_for_minute = max(
            guard_ids, key=lambda guard_id: guard_minutes[guard_id, minute]
        )
        if guard_minutes[sleepiest_guard_id_for_minute, minute] > sleep_time:
            sleep_time = guard_minutes[sleepiest_guard_id_for_minute, minute]
            sleepiest_guard_id = sleepiest_guard_id_for_minute
            safest_minute = minute
    return sleepiest_guard_id * safest_minute


def main() -> None:
    with Path(__file__).with_name("input.txt").open() as handle:
        events: T.List[Event] = []
        for i, line in enumerate(sorted(handle)):
            events.append(Event.from_line(line, events[-1] if i else None))
    print(part1(events))
    print(part2(events))


if __name__ == "__main__":
    main()
